[package]
name = "rusty-react"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
state = { version = "0.5", features = ["tls"] }
lazy_static = "1.4"
